INSERT INTO EMPLOYEE_DTL (EMPLOYEE_ID, EMPLOYEE_NM, EMPLOYEE_SAL, EMPLOYEE_ADDRS)
VALUES (101, 'Santosh', 20000, 'Ramapuram');

INSERT INTO EMPLOYEE_DTL (EMPLOYEE_ID, EMPLOYEE_NM, EMPLOYEE_SAL, EMPLOYEE_ADDRS)
VALUES (102, 'Mousumee', 40000, 'Odisha');
