DROP TABLE IF EXISTS EMPLOYEE_DTL;
DROP TABLE IF EXISTS FILE_UPLOAD;

CREATE TABLE EMPLOYEE_DTL
(
	EMPLOYEE_ID NUMBER,
	EMPLOYEE_NM VARCHAR2(20 BYTE),
	EMPLOYEE_SAL NUMBER,
	EMPLOYEE_ADDRS VARCHAR (20 BYTE)

);

CREATE TABLE FILE_UPLOAD
(
	FILE_ID NUMBER,
	FILE_NM VARCHAR2 (50 BYTE),
	FILE_CONTENT BLOB,
	CRTE_DT DATE
);
